### ISSUE TITLE
competitive companion without new session or open new session in a new tab

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#32]
**Is your feature request related to a problem? Please describe.**

If I want to use competitive companion, and I've already written the codes, it's not convenient that the editor will open a new session.

**Describe the solution you'd like**

There can be a message box to choose whether to open a new session or not.

Also, now there is a reason to support multiple tabs which is described in #13.

Since the competitive companion is supported, it would be nice if the new session is opened in the same window but a new tab (since opening a new window listening to the same port is technically unfeasible).

Hence, competitive companion for a whole contest can be also supported (and there can be no message box for contest parsing).

**Describe alternatives you've considered**

Won't support multiple tabs, but only a message box to choose whether to open a new session or not.

**Additional context**

N/A

**Comment by coder3101** [comment]
When i initially decided to add Competitive Companion this was indeed my priority. A way to let user accept or deny the request for new session. But problem is that for that the message pops up and application crashes because for pop ups to be produced, the running window should be visible. However when you send request from browser, the editor is in background, so it doesn't or cannot produce a confirmation pop up.

**Comment by ouuan** [comment]
If the popup window is not feasible, I think an option is also good. For me, I don't really care about the header, so I'd like to not open a new session.

**Comment by ouuan** [comment]
BTW, since there are more and more settings, maybe it's good to place them in a "preferences" popup.

**Comment by ouuan** [comment]
It is fixed by #44 .
